version: '3'

services:
  postgres:
    build:
      context: ./postgres-db
    ports:
      - "5429:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.19
    volumes:
      - "./changelog:/liquibase/changelog"
    command: >
      --url="jdbc:postgresql://postgres:5432/omega"
      --changeLogFile=/changelog/changelog-master.yaml
      --username=nonroot
      --password=nonroot
      update
    depends_on:
      postgres:
        condition: service_healthy

  # Upload with us-east-1 region or it will throw an exception
  s3:
    image: bitnami/minio:latest
    ports:
      - "8000:9000"
      - "8001:9001"
    expose:
      - 9000
    environment:
      - MINIO_ROOT_USER=accessKey1
      - MINIO_ROOT_PASSWORD=verySecretKey1
      - MINIO_DEFAULT_BUCKETS=audio,video,image

#  aws-cli:
#    image: amazon/aws-cli:latest
#    command: |
#      "
#      aws configure set aws_access_key_id accessKey1
#      aws configure set aws_secret_access_key verySecretKey1
#      aws configure set default.region us-east-1
#
#      aws s3api create-bucket --bucket test-bucket-989282 --endpoint-url http://s3:9000
#      "

