version: '3'

services:
  gateway:
    build:
      context: ./gateway
    command: java -jar app.jar --spring.profiles.active=prod
    volumes:
      - ./config/gateway:/content/config
    expose:
      - 8080
    depends_on:
      liquibase:
        condition: service_completed_successfully

  robot:
    build:
      context: ./ro-bot
    command: java -jar app.jar --spring.profiles.active=prod
    volumes:
      - ./config/ro-bot:/content/config
    expose:
      - 8080
    depends_on:
      liquibase:
        condition: service_completed_successfully

  neural-text:
    build:
      context: ./neural-text
    command: uvicorn app:app
    expose:
      - 8080
    environment:
      SERVER_PORT: 8080
      SERVER_MODEL_NAME_OR_PATH: Nothing
      SERVER_USE_STUB: true
      PYTHONUNBUFFERED: 1

  postgres:
    build:
      context: ./postgres-db
    ports:
      - "5429:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.19
    volumes:
      - "./changelog:/liquibase/changelog"
    command: >
      --url="jdbc:postgresql://postgres:5432/omega"
      --changeLogFile=/changelog/changelog-master.yaml
      --username=nonroot
      --password=nonroot
      update
    depends_on:
      postgres:
        condition: service_healthy

#  s3:
#    image: scality/s3server:latest
